### ISSUE TITLE
unable to generate acess token

### ISSUE THREAD

**Issue by saikumarjnet** [jeremykenedy/laravel-passport#1]
http://localhost:8080/lumen/public/oauth/token?grant_type=client_credientials&password=123123&client_id=2&client_secret=8xZG8EPENu4CkbnQjahIlRmgJ6xuHc8WUx3O5lF5&email=hash@jkhaks.jkjkahs&scope=*

getting this error in post man
{"error":"unsupported_grant_type","message":"The authorization grant type is not supported by the authorization server.","hint":"Check the `grant_type` parameter"}

i have changed grant type to password also still error is smae

**Comment by jeremykenedy** [comment]
I don't know, this is an out the box implementation of Laravel Passport. You will need to take it up directly with the package authors and do some debugging on your own.

**Comment by jeremykenedy** [comment]
https://stackoverflow.com/questions/41398996/laravel-passport-grant-type-not-supported
